spring:
    jpa:
        properties:
            hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 5
    h2:
        console:
            enabled: true

logging:
    level:
        io.geemov42: DEBUG
        sql: debug
